play {
  http.port=9001
  filters {
    hosts {
      allowed = ["."]
    }
  }
}

job {
  runner = [docker]
}

analyzer {
  path = ["tmp/cortex-jobs/analyzers"]
}

responder {
  path = ["tmp/cortex-jobs/responders"]
}

## Enable CQL for Cortex
db {
  provider: janusgraph
  janusgraph {
    storage {
      backend: cql
      hostname: ["elasticsearch"]
      cql {
        cluster-name: thp
        keyspace: cortex
      }
    }
    index {
      search {
        backend: elasticsearch
        hostname: ["elasticsearch"]
        index-name: cortex
      }
    }
  }
}
