play {
  http.port=9000
  filters {
    hosts {
      allowed = ["."]
    }
  }
}

storage {
  provider = localfs
  localfs {
    location = "/opt/thp/thehive/data"
  }
}

## Enable CQL for TheHive
db {
  provider: janusgraph
  janusgraph {
    storage {
      backend: cql
      hostname: ["elasticsearch"]
      cql {
        cluster-name: thp
        keyspace: thehive
      }
    }
    index {
      search {
        backend: elasticsearch
        hostname: ["elasticsearch"]
        index-name: thehive
      }
    }
  }
}

## Configure TheHive to connect to Cortex
cortex {
  "local" {
    url = "http://cortex:9001"
  }
}

## Configure TheHive to connect to MISP
misp {
  "MISP THP" {
    url = "https://misp"
    ws {
      ssl {
        trustAll = true
      }
    }
  }
}
